More versatile list function
rayepps/radash pull request #33
Opened 2022-08-29 15:03 UTC by dolsem

Right now the `list` function does not add a lot of value; it just wraps `range` in `Array.from`. I propose a more versatile function while maintaining strong typing. Here are some usage examples:

```js
list(5) // => [undefined, undefined, undefined, undefined, undefined]
list(5, {}) // => [{}, {}, {}, {}, {}]
list(5, Math.random) // => <random number>[5]
list(range(2, 10, 2)) // => [2, 4, 6, 8, 10]
list(range(97, 107, 2), (x) => String.fromCharCode(x)) // => ['a', 'c', 'e', 'g', 'i', 'k']
```

Array allocation has always been awkward in JavaScript compared to something like Python, and honestly, I could see myself using **radash** for this function alone, if this does get merged.

2022-08-30 00:17 UTC, rayepps requested changes
Thanks for the PR @dolsem , I like the idea a lot. The changes have errors. If you want to get those fixed and update/add tests to cover the new cases I'd be happy to merge.

A few thoughts, I think we can simplify the types a bit
```ts
export const list = <T=number> (
  lengthOrGenerator: Generator<number> | number,
  valueOrMapper?: T | ((num: number) => T)
): T[] => {
  return [] // do actual work
}
```

Thanks for updating the examples, it makes the intent super clear. Can you add one more case, where it's called with only the first arg `list(3)` which should produce `[1, 2, 3]`

2022-08-30 20:24 UTC, dolsem commented
> Can you add one more case, where it's called with only the first arg list(3) which should produce [1, 2, 3]

Hey, so my intention was actually this: if the first argument is an iterable, create array from that iterable. If the first argument is a number, use that as the size of the array and populate it with the second argument. Sometimes you just want an array of 3 empty objects, in which case you can do `list(3, {})`. Or just an empty array of size 3, so you can do `list(3)` and get `[undefined, undefined, undefined]`. To get `[1, 2, 3]` with this implementation, you can do `list(range(1, 3, 1))` or `list(3, (_, i) => i+1)`.

I know this is a breaking change, but in case you like it, mb we could consider this for the next major release? The current functionality can easily be replaced with `Array.from(range(...args))`, and besides, if I saw `list(3)` in someone's code without knowing the library, I wouldn't be able to guess it returns `[1, 2, 3]`, I would expect an empty array of size 3. After all, numbers are just one of the many possible datatypes arrays are used with.

2022-08-31 01:23 UTC, rayepps commented
I don't mind the breaking change for this. You have to realize this library might seem _popular_ but it's only been used by the community for like 4 days 😆 Also, for this specifically I think it's a huge improvement so I'm stoked to get it in.

Can you tell me a bit more about what you mean when you say 'iterable'. I think I might be a wee bit confused. If you're passing an iterable into list... what value does list provide--aside from mapping?

I see what you're saying, it makes more sense. I'm not a fan of `list(3)` producing `[undefined, undefined, undefined]`. There might be a use case where you want a list of 3 undefined values but in my experience, it's the edge case. By default, I'd like the array I get back to be ordered ints. I'm open to having my mind changed on this, especially cus I think I might not be understanding your intent correctly.

Could you provide a few more examples? Or maybe write up the tests first, with input => output, so the use cases are super obvious.

2022-08-31 03:40 UTC, dolsem commented
> Can you tell me a bit more about what you mean when you say 'iterable'

In TypeScript terms, something that conforms to the [Iterable interface](https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html). More concretely, an object that has the `Symbol.iterator` property, and so can be iterated over, e.g. using the `for..of` loop or the spread operator. I believe the return type of your `range()` function is an Iterable. So `list` can use a generator to create and populate an array with each iteration. Your original implementation did exactly that, it can just be generalized to any generator/iterable, not just the `range()` one.

> Could you provide a few more examples? Or maybe write up the tests first, with input => output, so the use cases are super obvious.

I'll try to find some time for it tomorrow.

2022-09-13 13:54 UTC, dolsem commented
@rayepps I pushed test cases and fixed a typo in the implementation. Hopefully this helps illustrate my idea and why I chose such behavior.

2022-09-23 06:32 UTC, dolsem commented
@rayepps any thoughts?

2022-10-14 00:16 UTC, rayepps commented
Hey @dolsem, apologies for being away.

A few thoughts,

1. I don't want to use iterable as an input parameter. It might be _convenient_ to some but I'd prefer to keep input/output to strictly primitives, objects, arrays, and functions.
2. I don't want the consumer to have to pass range, it's just a bit awkward and clunky (more of an IMHO)
3. We have to find a simpler way to implement this... the types alone here are too complicated.
4. I want to optimize for the most common use case in priority order, IME after using radash for a few years that's `list(5)`, then `list(2, 5)`, then `list(2, 5).map(mapper)`
5. For the arguments, I'd like them to be as consistent as possible. I'm ok with overloads but at most one per function.

All these thoughts lead me to this solution:

```ts
type IntMapFn<T> = (i: number) => T

/**
 * Creates a list of given start, end, value, and step parameters
 *
 * list(3)                  // 0, 1, 2, 3
 * list(0, 3)               // 0, 1, 2, 3
 * list(0, 3, 'y')          // y, y, y, y
 * list(0, 3, () => 'y')    // y, y, y, y
 * list(0, 3, i => i)       // 0, 1, 2, 3
 * list(0, 3, i => `y${i}`) // y0, y1, y2, y3
 * list(0, 3, obj)          // obj, obj, obj, obj
 * list(0, 6, i => i, 2)    // 0, 2, 4, 6
 *
 * list = (length) => [...]
 * list = (start, end, value?, step?) => [...]
 */
export const list = <T = number>(
  startOrLength: number,
  end: number = startOrLength,
  value: T | IntMapFn<T> = (i: number) => i as T,
  step: number = 0
): T[] => {
  const start = end ? startOrLength : 0
  const mapFn = isFunction(value) ? (value as IntMapFn<T>) : () => value as T
  return Array.from(range(start, end, step), mapFn)
}
```

As the engineer working hard on an open source repo I know this might be frustrating. These things are what set Radash apart from Lodash.

Please let me know what you think, I welcome opinionated feedback and nits :)

2022-11-09 21:45 UTC, rayepps commented
Hey @dolsem I'm gonna close this since there hasn't been activity for a while.

2022-11-09 21:45 UTC, closed without merging